[platformio]
default_envs = native_hil

[env:native_hil]
platform = file://../vendor/platform-native
lib_extra_dirs = ../shared
build_flags = -std=c++17 -Wall -Wextra -Werror
build_unflags = -std=gnu++11
