[platformio]
default_envs = esp32_fertigation

[env:esp32_fertigation]
platform = https://github.com/platformio/platform-espressif32.git#11f8c40be7591c82858b6f7cd310cb166a5d2e3e
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../shared
lib_deps =
  https://github.com/PaulStoffregen/OneWire.git#72249e22ef9092b0750e303d266199965a89e500
  https://github.com/milesburton/Arduino-Temperature-Control-Library.git#3f570bbe2d0ad3cae55663cfaec1fedbc5b4fa50
  https://github.com/bogde/HX711.git#01e8a1e8eb22d4380f83194e266a2f75ea0c993c
build_flags = -std=gnu++17 -Wall -Wextra
build_unflags = -std=gnu++11
