per_listener_settings true
listener 8883 0.0.0.0
protocol mqtt

allow_anonymous false
require_certificate true
use_identity_as_username true
tls_version tlsv1.3
cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/server.crt
keyfile /mosquitto/config/certs/server.key
acl_file /mosquitto/config/growhub.acl

persistence true
persistence_location /mosquitto/data/
autosave_interval 60
max_queued_messages 1000
max_inflight_messages 20
message_size_limit 65536
retain_available true

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
