[platformio]
default_envs = esp32_climate

[env:esp32_climate]
platform = https://github.com/platformio/platform-espressif32.git#11f8c40be7591c82858b6f7cd310cb166a5d2e3e
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../shared
lib_deps =
  https://github.com/adafruit/Adafruit_BME280_Library.git#ef712e95147de926b4545e379f6296ad271529b5
  https://github.com/adafruit/Adafruit-MLX90614-Library.git#8c32c95768e0960d7c27258b1d9bac16b8d7fdfc
build_flags = -std=gnu++17 -Wall -Wextra
build_unflags = -std=gnu++11
