[platformio]
default_envs = esp32_diy_controller

[env:esp32_diy_controller]
platform = https://github.com/platformio/platform-espressif32.git#11f8c40be7591c82858b6f7cd310cb166a5d2e3e
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../shared
lib_deps =
  https://github.com/adafruit/DHT-sensor-library.git#2295fe471c38d5e649a7b68cecccc42193c8e41c
build_flags = -std=gnu++17 -Wall -Wextra
build_unflags = -std=gnu++11

[env:native_syntax]
platform = file://../vendor/platform-native
lib_extra_dirs = ../shared
build_flags =
  -std=c++17
  -Wall
  -Wextra
  -Werror
  -DARDUINO=10800
  -I native-stubs
